[build]
  command = "npm run build:css:prod && remix build && echo 'Explore root directory' && ls && "public folder" && cd /opt/build/repo/remix-gql-tailwind/public && ls"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
