const { writeFile } = require('fs');
const path = require('path');
const colors = require('colors');
const dotenv = require('dotenv');

// get .env vars
dotenv.config();
const targetPath = path.join(__dirname, '../src/environments/environment.ts');

const envVars = `export const environment = {
  production: ${process.env.PRODUCTION},
  apiUrl: '${process.env.OAUTH_API_URL}',
  graphApiUrl: '${process.env.GITHUB_GRAPHQL_URL}',
  redirectUrl: '${process.env.CLIENT_REDIRECT_URL}',
};`;

// `environment.ts` file structure
const envConfigFile = `/*** DO NOT EDIT THIS FILE BEFORE READING THIS
 * If this line is here, then this file was re-generated by running \`npm run config\`.
 * To modify:
 * - Create a \`.env\` file at project root (this will be gitignored by default)
 * - Change any environment variables there
 * - Change any add the, to the  variables there
 DO NOT EDIT THIS FILE BEFORE READING THIS */

// This file can be replaced during build by using the \`fileReplacements\` array.
// \`ng build\` replaces \`environment.ts\` with \`environment.prod.ts\`.
// The list of file replacements can be found in \`angular.json\`.

${envVars}

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as \`zone.run\`, \`zoneDelegate.invokeTask\`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
`;

console.log(
  colors.magenta(
    'The file `environment.ts` will be written with the following content: \n',
  ),
);
console.log(colors.grey(envConfigFile));

writeFile(targetPath, envConfigFile, (err) => {
  if (err) {
    throw console.error(err);
  }

  console.log(
    colors.magenta(
      `Angular environment.ts file generated correctly at ${targetPath} \n`,
    ),
  );
});
