service: starter-dev-backend
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-domain-manager
  - serverless-bundle
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
  customDomain:
    domainName: api.starter.dev
    stage: production
    endpointType: 'regional'
    apiType: http
    certificateName: '*.starter.dev'

provider:
  name: aws
  profile: starterdev
  stage: ${sls:stage}
  region: ${opt:region}
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
