service: starter-dev-backend
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-domain-manager
  - serverless-bundle
  - serverless-offline

custom:
  bundle:
    packager: yarn

  customDomain: # serverless-domain-manager
    domainName: api.starter.dev
    stage: production
    endpointType: 'regional'
    apiType: http
    certificateName: '*.starter.dev'

  serverless-offline: # serverless-offline
    httpPort: 4000

provider:
  name: aws
  profile: starterdev
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
