export enum ORDER_BY_FIELD {
  UPDATED_AT = 'UPDATED_AT',
  CREATED_AT = 'CREATED_AT',
  PUSHED_AT = 'PUSHED_AT',
  NAME = 'NAME',
  STARGAZERS = 'STARGAZERS',
}

export enum ORDER_BY_DIRECTION {
  ASC = 'ASC',
  DESC = 'DESC',
}
