export const issues = {
  open: [
    {
      number: '33',
      title: 'This is just a test title',
      cardType: 'issue',
      url: '',
      state: 'OPEN',
      createdAt: '03-20-2020',
      authorName: 'MC Turtles',
      commentCount: 3,
      labels: [],
      isOpen: true,
    },
    {
      number: '33',
      title: 'This is just a test title',
      cardType: 'issue',
      url: '',
      state: 'OPEN',
      createdAt: '03-20-2021',
      authorName: 'MC Turtles',
      commentCount: 3,
      labels: [],
      isOpen: false,
    },
    {
      number: '33',
      title: 'This is just a test title',
      cardType: 'issue',
      url: '',
      state: 'OPEN',
      createdAt: '03-20-2021',
      authorName: 'MC Turtles',
      commentCount: 3,
      labels: [],
      isOpen: false,
    },
  ],
  closed: [
    {
      number: '33',
      title: 'This is just a test title',
      cardType: 'issue',
      url: '',
      state: 'CLOSED',
      createdAt: '03-20-2020',
      authorName: 'MC Turtles',
      commentCount: 3,
      labels: [],
      isOpen: true,
    },
    {
      number: '33',
      title: 'This is just a test title',
      cardType: 'issue',
      url: '',
      state: 'CLOSED',
      createdAt: '03-20-2021',
      authorName: 'MC Turtles',
      commentCount: 3,
      labels: [],
      isOpen: false,
    },
    {
      number: '33',
      title: 'This is just a test title',
      cardType: 'issue',
      url: '',
      state: 'CLOSED',
      createdAt: '03-20-2021',
      authorName: 'MC Turtles',
      commentCount: 3,
      labels: [],
      isOpen: false,
    },
  ],
};
