export const container = 'my-6 flex items-center';
export const btn = 'relative inline-flex items-center px-4 py-1 rounded-md bg-gray-50 border border-gray-300 font-medium text-gray-700 hover:bg-gray-200 hover:bg-opacity-50';
export const btnIcon = 'w-5 h-5 text-gray-600 mr-1';
export const btnCaret = 'font-size: 10px text-gray-600 ml-1.5 mt-0.5';
export const separator = 'text-lg text-gray-800 leading-snug mx-1.5';
export const rootLink = 'font-semibold text-blue-600 hover:underline';
export const crumbs = 'flex px-3';
export const crumbLink = 'text-blue-600 hover:underline';
export const crumbEnd = 'font-semibold';
