export const TABS = {
  OPEN: 'open',
  CLOSED: 'closed',
};

export const PULL_REQUESTS = {
  openPullRequest: [
    {
      state: 'OPEN',
      createdAt: '20 sep 2020',
      closedAt: null,
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'OPEN',
      createdAt: '20 sep 2020',
      closedAt: null,
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'OPEN',
      createdAt: '20 sep 2020',
      closedAt: null,
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'OPEN',
      createdAt: '20 sep 2020',
      closedAt: null,
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'OPEN',
      createdAt: '20 sep 2020',
      closedAt: null,
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'OPEN',
      createdAt: '20 sep 2020',
      closedAt: null,
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
  ],
  closedPullRequest: [
    {
      state: 'MERGED',
      createdAt: '20 sep 2020',
      closedAt: '20 sep 2022',
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'MERGED',
      createdAt: '20 sep 2020',
      closedAt: '20 sep 2022',
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'MERGED',
      createdAt: '20 sep 2020',
      closedAt: '20 sep 2022',
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'MERGED',
      createdAt: '20 sep 2020',
      closedAt: '20 sep 2022',
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'MERGED',
      createdAt: '20 sep 2020',
      closedAt: '20 sep 2022',
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'MERGED',
      createdAt: '20 sep 2020',
      closedAt: '20 sep 2022',
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'CLOSED',
      createdAt: '20 sep 2020',
      closedAt: '20 sep 2022',
      comments: { totalCount: 3 },
      number: 121,
      author: { login: 'Dustin' },
      title: 'Save The last code',
      url: '#',
    },
  ],
};
