export const TABS = {
  OPEN: 'open',
  CLOSED: 'closed',
};

export const PULL_REQUESTS = {
  openPullRequest: [
    {
      state: 'OPEN',
      createdAt: new Date(),
      closedAt: null,
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'OPEN',
      createdAt: new Date(),
      closedAt: null,
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'OPEN',
      createdAt: new Date(),
      closedAt: null,
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'OPEN',
      createdAt: new Date(),
      closedAt: null,
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'OPEN',
      createdAt: new Date(),
      closedAt: null,
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'OPEN',
      createdAt: new Date(),
      closedAt: null,
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
  ],
  closedPullRequest: [
    {
      state: 'MERGED',
      createdAt: new Date(),
      closedAt: new Date(),
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'MERGED',
      createdAt: new Date(),
      closedAt: new Date(),
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'MERGED',
      createdAt: new Date(),
      closedAt: new Date(),
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'MERGED',
      createdAt: new Date(),
      closedAt: new Date(),
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'CLOSED',
      createdAt: new Date(),
      closedAt: new Date(),
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'MERGED',
      createdAt: new Date(),
      closedAt: new Date(),
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
    {
      state: 'CLOSED',
      createdAt: new Date(),
      closedAt: new Date(),
      comments: 3,
      number: '121',
      author: 'Dustin',
      title: 'Save The last code',
      url: '#',
    },
  ],
};
