# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular NgRx SCSS CI

on:
  push:
    branches: [main]
    paths:
      - "angular-ngrx-scss/**"
  pull_request:
    branches: [main]
    paths:
      - "angular-ngrx-scss/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: angular-ngrx-scss/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: angular-ngrx-scss

      - name: Lint files
        run: npm run lint
        working-directory: angular-ngrx-scss

  format-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: angular-ngrx-scss/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: angular-ngrx-scss

      - name: Check formatting
        run: npm run format:check
        working-directory: angular-ngrx-scss

  build:
    runs-on: ubuntu-latest
    needs: [lint, format-check]

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: angular-ngrx-scss/package-lock.json

      - name: Install dependencies
        run: npm ci

        working-directory: angular-ngrx-scss
      - name: Build Project
        run: npm run build
        working-directory: angular-ngrx-scss

  test:
    runs-on: ubuntu-latest
    needs: [lint, format-check]

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: angular-ngrx-scss/package-lock.json

      - name: Install dependencies
        run: npm ci

        working-directory: angular-ngrx-scss
      - name: Test Project
        run: npm run test:ci
        working-directory: angular-ngrx-scss
  conditional_job_check_files:
    runs-on: 'ubuntu-20.04'
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '^docs/' -or $_ -match '.md$' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "docs_changed"
        Write-Host "::set-output name=docs_changed::$HasDiff"

  # Run the job only with "docs_changed" equals "True"
  conditional_job:
    runs-on: 'ubuntu-20.04'
    needs: [ conditional_job_check_files ]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'True'
    steps:
    - shell: pwsh
      run: echo publish docs