# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Qwik Graphql Tailwind CI

on:
  push:
    branches: [main]
    paths:
      - 'qwik-graphql-tailwind/**'
  pull_request:
    branches: [main]
    paths:
      - 'qwik-graphql-tailwind/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: qwik-graphql-tailwind/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: qwik-graphql-tailwind

      - name: Lint files
        run: yarn lint
        working-directory: qwik-graphql-tailwind

  format-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: qwik-graphql-tailwind/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: qwik-graphql-tailwind

      - name: Check formatting
        run: yarn prettier.check
        working-directory: qwik-graphql-tailwind

  build:
    runs-on: ubuntu-latest
    needs: [lint, format-check]

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: qwik-graphql-tailwind/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: qwik-graphql-tailwind

      - name: Build Project
        run: yarn build
        working-directory: qwik-graphql-tailwind

  test:
    runs-on: ubuntu-latest
    needs: [lint, format-check]

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: qwik-graphql-tailwind/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: qwik-graphql-tailwind

        working-directory: qwik-graphql-tailwind
      - name: Test Project
        run: yarn test
        working-directory: qwik-graphql-tailwind
