name: Solid Start Tanstack Query Tailwind Modules CI

on:
  push:
    branches: [main]
    paths:
      - "solidstart-tanstackquery-tailwind-modules/**"
  pull_request:
    branches: [main]
    paths:
      - "solidstart-tanstackquery-tailwind-modules/**"


jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: solidstart-tanstackquery-tailwind-modules

      - name: Lint files
        run: npm run lint
        working-directory: solidstart-tanstackquery-tailwind-modules
  

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: solidstart-tanstackquery-tailwind-modules

      - name: Run tests
        run: npm run test
        working-directory: solidstart-tanstackquery-tailwind-modules

  
  build:
    runs-on: ubuntu-latest
    needs: [lint, run-unit-tests]

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: solidstart-tanstackquery-tailwind-modules

      - name: Build Project
        run: npm run build
        working-directory: solidstart-tanstackquery-tailwind-modules