# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sveltekit and SCSS CI

on:
  push:
    branches: [main]
    paths:
      - 'svelte-kit-scss/**'
  pull_request:
    branches: [main]
    paths:
      - 'svelte-kit-scss/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm run'
          cache-dependency-path: svelte-kit-scss/package-lock.json

      - name: Install dependencies
        run: npm install --frozen-lockfile
        working-directory: svelte-kit-scss

      - name: Lint files
        run: npm run lint
        working-directory: svelte-kit-scss

  format-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm run'
          cache-dependency-path: svelte-kit-scss/package-lock.json

      - name: Install dependencies
        run: npm install --frozen-lockfile
        working-directory: svelte-kit-scss

      - name: Check formatting
        run: npm run format:check
        working-directory: svelte-kit-scss

  test: 
    runs-on: ubuntu-latest
    needs: [lint, format-check]
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm run'
          cache-dependency-path: svelte-kit-scss/package-lock.json

      - name: Install dependencies
        run: npm install --frozen-lockfile
        working-directory: svelte-kit-scss

      - name: Run Tests
        run: npm test
        working-directory: svelte-kit-scss
  
  test-e2e: 
    runs-on: ubuntu-latest
    needs: [lint, format-check]
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm run'
          cache-dependency-path: svelte-kit-scss/package-lock.json

      - name: Install dependencies
        run: npm install --frozen-lockfile
        working-directory: svelte-kit-scss

      - name: Run E2E Tests
        run: npm test:e2e
        working-directory: svelte-kit-scss

  build:
    runs-on: ubuntu-latest
    needs: [lint, format-check, test]

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm run'
          cache-dependency-path: svelte-kit-scss/package-lock.json

      - name: Install dependencies
        run: npm install --frozen-lockfile
        working-directory: svelte-kit-scss

      - name: Build Project
        run: npm run build
        working-directory: svelte-kit-scss
