name: Solidjs TailwindCSS CI

on:
  push:
    branches: [main]
    paths:
      - "solidjs-tailwind/**"
  pull_request:
    branches: [main]
    paths:
      - "solidjs-tailwind/**"


jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: solidjs-tailwind/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: solidjs-tailwind

      - name: Lint files
        run: pnpm run lint
        working-directory: solidjs-tailwind
  

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: solidjs-tailwind/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: solidjs-tailwind

      - name: Run tests
        run: pnpm run test
        working-directory: solidjs-tailwind

  
  build:
    runs-on: ubuntu-latest
    needs: [lint, run-unit-tests]

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: solidjs-tailwind/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: solidjs-tailwind

      - name: Build Project
        run: pnpm run build
        working-directory: solidjs-tailwind